import {ConnectButton} from "@rainbow-me/rainbowkit";
import type {NextPage} from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {Button, Image, Progress, Input} from "@chakra-ui/react";
import contractAbi from "../public/AICreations.json"
import React, {useState} from "react";
import {Contract} from "ethers";
import {useAccount, useSigner} from "wagmi";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const Home: NextPage = () => {

        const [promptInput, setPromptInput] = useState<string>("");
        const [creatureImg, setCreatureImg] = useState<string>("https://replicate.com/api/models/lambdal/text-to-pokemon/files/4d12a241-fd84-4b0a-8321-80dd8c6ae784/out-0.png");
        const [isLoading, setLoading] = useState<boolean>(false);
        const [prediction, setPrediction] = useState(null);
        const {address} = useAccount();
        const {data: signer} = useSigner();

        async function generateCreature(e: React.MouseEvent<HTMLButtonElement>) {
            e.preventDefault();
            setLoading(true);
            const response = await fetch("/api/creature", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({prompt: promptInput}),
            });

            if (response.status !== 201) {
                throw new Error(`Error: ${response.status}`);
            }

            let prediction = await response.json();
            setPrediction(prediction);
            while (
                prediction.status !== "succeeded" &&
                prediction.status !== "failed"
                ) {
                await sleep(500);
                console.log("waiting for prediction to finish " + prediction.id);
                const response = await fetch("/api/predictions/" + prediction.id);
                prediction = await response.json();
                if (response.status !== 200) {
                    console.log(prediction.detail);
                    return;
                }
                console.log({prediction})
                setPrediction(prediction);
                if (prediction.output != null)
                    setCreatureImg(prediction.output[prediction.output.length - 1]);
                setLoading(false);
            }

        }

        function handlePromptInput(e: React.ChangeEvent<HTMLInputElement>) {
            setPromptInput(e.target.value)
        }

        async function mintNft() {
            setLoading(true);
            const response = await fetch("/api/ipfs", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({prompt: promptInput, image_url: creatureImg}),
            });

            if (!response.ok) {
                throw new Error(`Error: ${response.status}`);
            }

            const data = await response.json();
            console.log('POST: ', data);
            console.log("Minting NFT");
            const nftContract = new Contract('0x5cBeEBfFb922377dce34307167c95585A00C1721', contractAbi.abi, signer);
            try {
                const mintTx = await nftContract.safeMint(address, data.ipfs_url);
                setLoading(false);
                console.log(mintTx?.hash);
                await mintTx.wait();
            } catch (e) {
                console.log(e);
                setLoading(false);
            }
        }

        return (
            <div className={styles.container}>
                <Head>
                    <title>RainbowKit App</title>
                    <meta
                        name="description"
                        content="Generated by @rainbow-me/create-rainbowkit"
                    />
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <ConnectButton/>

                    <h1 className={styles.title}>AI Creature generator</h1>

                    <p className={styles.description}>
                        To generate a new AiMon press Generate and wait a few seconds.
                    </p>
                    <p className={styles.subtitle}>
                        To unlock <b>evolutions</b> mint your creature as an NFT on the
                        Polygon network.
                    </p>

                    <p className={styles.subtitle}>
                        To unlock <b>evolutions</b> mint your creature as an NFT on the
                        Polygon network.
                    </p>
                    <div className={styles.grid}>
                        <div className={styles.card}>
                            <Input
                                value={promptInput}
                                onChange={handlePromptInput}
                                placeholder="Your AiMon prompt - example: baby yoda"
                                margin={2}
                            />
                            <Button onClick={generateCreature} colorScheme="blue" margin={2}>
                                Generate
                            </Button>

                            {isLoading &&
                                <div><Progress size='sm' isIndeterminate/>
                                    {prediction && (
                                        <div>
                                            <p>status: {prediction.status}</p>
                                        </div>
                                    )} </div>
                            }

                            <Image
                                margin={5}
                                boxSize="450px"
                                src={creatureImg}
                                alt="Creature"
                            />
                            <div className={styles.card}>
                                <p>Level: 1</p>
                                <p>HP: 100</p>
                                <p>Attack: 100</p>
                                <p>Defense: 100</p>
                                <p>Speed: 100</p>
                                <p>Special: 100</p>
                            </div>
                            <Button onClick={mintNft} colorScheme="blue" margin={2}>
                                Mint
                            </Button>

                            <Button colorScheme="blue" disabled margin={2}>
                                Evolve
                            </Button>
                        </div>

                    </div>
                </main>

                <footer className={styles.footer}>
                    <a href="https://stevyhacker.github.io" target="_blank" rel="noopener noreferrer">
                        Made by @stevyhacker
                    </a>
                </footer>
            </div>
        );
    }
;

export default Home;
